Cancel zoomToPoints if searchIndex is undefined
flekschas/regl-scatterplot pull request #124
Opened 2023-04-26 12:08 UTC by insertmike

Cancel zoomToPoints if `searchIndex` is undefined

## Description

> What was changed in this pull request?

Cancel `zoomToPoints` if `searchIndex` is not defined

> Why is it necessary?

Fixes #123

## Checklist

- [x] Provided a concise title as a [semantic commit message](https://www.conventionalcommits.org) (e.g. "fix: correctly handle undefined properties")
- [ ] Updated CHANGELOG.md
- [ ] Added or updated Tests added or updated
- [ ] Documentation added or updated in README.md
- [ ] Example(s) added or updated
- [ ] Screenshot, gif, or video attached for visual changes

2023-04-26 12:11 UTC, insertmike commented
@flekschas Shall we throw warning?

2023-04-27 01:34 UTC, flekschas requested changes
Thanks for taking a stab at this! I proposed some code changes to make the function return a rejected Promise instead of `false`. Also, there is an internal property called `isInit` that should be able to leverage to determine if the points have been initialized.

2023-04-27 01:34 UTC, flekschas commented on src/index.js
> +    }
```suggestion
    if (!isInit) return Promise.reject(new Error(ERROR_NOT_INITIALIZED))
```

Can you add the following line to the end of the `constants.js` file and import it?

```js
export const ERROR_NOT_INITIALIZED = 'Points have not been initialized yet';
```

2023-04-27 01:34 UTC, flekschas commented on tests/index.js
> +    await scatterplot.zoomToPoints([1, 2]);
```suggestion
    await scatterplot.zoomToPoints([1, 2]);
    try{
      await scatterplot.zoomToPoints([1, 2]);
      t.fail('zoomToPoints should have thrown an error');
    } catch(e) {
      t.equal(e.message, ERROR_NOT_INITIALIZED);
    }
```

2023-04-27 07:34 UTC, insertmike commented
Thanks for stepping in. I applied your changes, they do make sense! :)

2023-04-27 13:59 UTC, flekschas requested changes

2023-05-01 01:58 UTC, flekschas commented
Close this PR in favor of https://github.com/flekschas/regl-scatterplot/pull/126 which contains the changes from this PR (your commits are still there and will be merged!) as well as the necessary suggestions to get the test to pass.

Thanks again for taking a stab at this 🙏

2023-05-01 01:58 UTC, closed without merging

2023-05-02 08:35 UTC, insertmike commented
> Close this PR in favor of #126 which contains the changes from this PR (your commits are still there and will be merged!) as well as the necessary suggestions to get the test to pass.
> 
> Thanks again for taking a stab at this 🙏

Thank you for doing this! I was on vacation and this is why I didn't come to latest comments