fix: Inability to draw with active filter
flekschas/regl-scatterplot pull request #137
Opened 2023-06-21 09:34 UTC by insertmike

> Write one to two sentences summarizing this PR

## Description

> What was changed in this pull request?

> Why is it necessary?

Fixes #136 

## Checklist

- [x] Provided a concise title as a [semantic commit message](https://www.conventionalcommits.org) (e.g. "fix: correctly handle undefined properties")
- [x] `CHANGELOG.md` updated
- [x] Tests added or updated
- [x] Documentation in `README.md` added or updated
- [ ] Example(s) added or updated
- [ ] Screenshot, gif, or video attached for visual changes

2023-06-22 10:40 UTC, insertmike commented
@flekschas Does this look good?

2023-06-22 13:12 UTC, flekschas requested changes
Thanks for taking a stab at the issue. The code looks good overall but I left some comments for smaller adjustments

2023-06-22 13:12 UTC, flekschas commented on src/index.js
> +          if (!options.preventFilterReset) {
```suggestion
          if (!options.preventFilterReset || points?.length !== numPoints) {
```

2023-06-22 13:12 UTC, flekschas commented on src/index.js
> +            }
```suggestion
```

This can be merged into the above if statement. See my comment

2023-06-22 13:16 UTC, insertmike commented on README.md
> +  - `preventFilterReset` [default: `true`]: if `false`, the active filteredPoints set is not being reset.
My wrong. Good call!

2023-06-22 13:31 UTC, insertmike commented
Thanks for your dedication and review! @flekschas

I went through your code review and trying addressing all comments.

2023-06-23 13:47 UTC, flekschas approved these changes
Thanks for addressing my comments! The PR looks good now!

2023-06-23 13:47 UTC, merged

2023-06-23 14:28 UTC, insertmike commented
> Thanks for addressing my comments! The PR looks good now!

Amazing, thank you! Looking forward to more PR's. Are we planning on having a release anytime soon?

2023-06-23 14:32 UTC, flekschas commented
Yes, a release is imminent. Just putting another fix together